name: Report CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the report branch
  push:
    branches: [ report ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile-report:
    runs-on: ubuntu-latest
    name: A job to Compile Latex file

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            "doc/main.tex"
            "doc/title.tex"
            "doc/1-Introduzione.tex"